### ISSUE TITLE
Subjoin on Sample Names

### ISSUE THREAD

**Issue by ZwFink** [LadnerLab/PepSIRF#1]
Currently, the subjoin module only supports joining on peptide names. New default functionality should be added, allowing the joining on sample names. Joining on peptide names will be supported with the inclusion of a boolean flag. 

With this change comes the issue of handling duplicate sample names, which can happen as a result of rerunning the same sample multiple times. 
Thus far, 3 modes of duplicate handling have been identified:
- combining the duplicate counts (with addition)
- including duplicates, but appending the file the sample came from (excluding any path information)
- Only including one of the duplicates.

More may be added as deemed appropriate.
Different handling strategies should be identified, with the desired strategy being selectable at the invocation interface (CLI, GUI (eventual), etc.).

As a default, both should be included, but warnings should be generated when sample names are duplicated.

**Comment by jtladner** [comment]
"Joining on sample names will be supported with the inclusion of a boolean flag." - not sure exactly what you mean here, but joining on sample names should be default (no flag required), with joining on peptide names being an option specified with a flag.

**Comment by ZwFink** [comment]
Right, that's what I meant. Updated the issue.
