### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#10]
[2020-01-07_MacCompileError.txt](https://github.com/LadnerLab/PepSIRF/files/4032813/2020-01-07_MacCompileError.txt)

Just tried to compile the latest version and got the attached error.

**Comment by ZwFink** [comment]
I may have found the error, can you try to build the version in the ```bug_fix``` branch?

**Comment by jtladner** [comment]
Yup. That seems to have done it.
