### ISSUE TITLE
p_enrich - tracking why no enriched peptide file is generated for certain pairs

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#103]
When running p_enrich, some sample pairs may not result in the generation of an enriched peptide file. This can occur for two main reasons: 1) ≥1 of the replicates doesn't meet the specified raw read count threshold or 2) because none of the peptides met the peptide-levels thresholds for enrichment (e.g., Z score, norm read count, etc.). And, the relevant explanation can be different for different samples in the same run. 

Currently, there is no way for the user to know which of these reasons  applies to each sample that is missing a file. I propose the generation of a new output file that will track this information for each sample pair that doesn't result in the generation of an enriched peptide file. This file should be output to the same directory as the enriched peptide files, it should contain a header ("Replicate1\tReplicate2\tReason\n") and should contain one row for each sample pair for which an enriched peptide file is not generated. The "Reason" column should contain one of the following: "Raw read count threshold" or "No enriched peptides".

**Comment by vidalrmartinez** [comment]
p_enrich has been updated to enrich. We will need to think of a more flexible way to handle storing the replicates with their reason.
