### ISSUE TITLE
Error compiling pepsirf on Big Sur

### ISSUE THREAD

**Issue by eelko09** [LadnerLab/PepSIRF#117]
When trying to compile with cmake on Mac Big Sur got the following error:

clang: error: unsupported option '-fopenmp'

Altered the openMP section of CMakeLists.txt to add -Xpreprocessor before -fopenmp when setting CMAKE_CXX_FLAGS:

if(OpenMP_FOUND)
  message( "OpenMP enabled" )
  list( APPEND PepSIRF_LINK_LIBS OpenMP::OpenMP_CXX )
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} **-Xpreprocessor** -fopenmp")
  add_definitions( -DENABLE_OPENMP )

else()
  message( "WARNING: OpenMP not found, parallelism disabled." )
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-unknown-pragmas -Wno-unused-value")
endif()

**Comment by jtladner** [comment]
@vidalrmartinez - Can you please check to see if the addition Evan described is problematic for compiling on Linux? If not, let's go ahead and add it. If it is a problem, can you make it so that this is automatically triggered on Mac systems?

**Comment by vidalrmartinez** [comment]
Closed with release 1.4.0
