### ISSUE TITLE
subjoin - Segment Fault 11

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#12]
If a matrix file is specified incorrectly to subjoin (i.e. file path does not actually exist), a segment fault 11 occurs, with no explanation of the problem. 

Please modify to quit with a warning if a particular file doesn't actually exist.

**Comment by ZwFink** [comment]
Error message now displays:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open file 'PV1-CombinedCounts_2Msum.tsv
[1]    16264 abort (core dumped)  ./pep_sirf subjoin --filter_scores PV1-CombinedCounts_2MM_colsum.tsv,names.tx

Although it's not pretty, it's clear that there was an error and the file that caused the error is shown.
