### ISSUE TITLE
Add enrich option for dropping replicates with low raw read counts

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#137]
Currently, if ≥1 replicate fails the raw read count threshold, the whole sample is ignored. 

This command line option would allow users to request that only the replicates with low read counts are dropped, with the analysis proceeding with the good replicates (assuming that ≥1 replicate passes the raw read count threshold).

**Comment by Num0Programmer** [comment]
Closed because implementation was pushed to master.
