### ISSUE TITLE
Enrich handling of singles/replicates

### ISSUE THREAD

**Issue by ekelley903** [LadnerLab/PepSIRF#141]
Update request to v1.4:
For identification of enriched peptides, add a flag for cases in which there are samples assayed a single time as well as samples run in replicates, i.e. an analysis with samples treated as "sEnrich" or "pEnrich" depending on whether they occur once in the sample list or if they have "_A, _B" suffixes.

**Comment by jtladner** [comment]
Functionality should be provided by "--p-flexible-reps-source" flag in q2-autopepsirf.

**Comment by jtladner** [comment]
Handled in Qiime2 plug-in
