### ISSUE TITLE
File Creation When No Enriched Peptides

### ISSUE THREAD

**Issue by Annabelle-Brown** [LadnerLab/PepSIRF#154]
Currently, with Pepsirf's enrich module, when there are no enriched peptides, no file is created. This is causing issues within q2-pepsirf's enrich module, as qiime needs a file of some sort, even when there are no enriched peptides, otherwise, q2-pepsirf's enrich module will fail with the current functionality.

A proposed solution is to have enrich create a file with the sample names whether the peptides are enriched or not. Files with no enriched peptides are to be empty, and files with enriched peptides are to be left as is.

**Comment by jtladner** [comment]
Issue redundant with #166.
