### ISSUE TITLE
No detection of failed enrichment in deconv

### ISSUE THREAD

**Issue by Clockwork-Rat** [LadnerLab/PepSIRF#161]
when passed a failed enrichment, deconv tries to deconvolve the "failedEnrichment.txt", should produce and error or warning

**Comment by jtladner** [comment]
Instead of specifically ignoring "failedEnrichment.txt", let's add a flag for the user to specify what string is expected at the end of each file containing enriched peptides. By default, this string should be "_enriched.txt".
