### ISSUE TITLE
Fastq Outputs

### ISSUE THREAD

**Issue by Clockwork-Rat** [LadnerLab/PepSIRF#169]
Create Sample-Specific FASTQ outputs with each run of demux. Sample specific versions of r1.

Anytime there is an index match to the point that a sample is known, that sequence output to a sample specific fastq file. These samples must be written out in real time, not saved into ram to save memory.

flag -q/--fastq_out +output directory
output as samplename_representation of index names.fastq

**Comment by Num0Programmer** [comment]
Issue solved in release of v1.6.0; more specifically, on Dec 24, 2022, demux-ISS169 was merged into develop (pull request #186). Later, improvements were made on Jan 16, 2023, when demux-ISS169 was merged into develop again (pull request #187).
