### ISSUE TITLE
module_demux::add_seqs_to_map Periodically causes a segfault 

### ISSUE THREAD

**Issue by ZwFink** [LadnerLab/PepSIRF#19]
Running ```pepsirf_test``` many times in a row reveals that ```module_demux::add_seqs_to_map``` periodically causes a segfault. When placing a pointer to a vector into a map, sometimes that pointer ends up having a null value.

**Comment by ZwFink** [comment]
Temporary fix in 69f74cbcd9d745482a90f710b93235c39362fc13, 'add_seqs_to_map' made sequential instead of parallel, as the bug only seems to occur when adding sequences to a parallel_map in parallel.

**Comment by jtladner** [comment]
Likely solved later while fixing issues with consistency of demux with multiple threads. Needed to lock threads at various places.
