### ISSUE TITLE
Remove warnings during compilation

### ISSUE THREAD

**Issue by Clockwork-Rat** [LadnerLab/PepSIRF#195]
Remove known warnings that occur during compile time.

**Comment by Num0Programmer** [comment]
Closed because this issue was solved with different build types for cmake.
If you would like to see the warnings you may run: "cmake -DCMAKE_BUILD_TYPE=Debug .." from the build directory.
Otherwise, running "cmake -DCMAKE_BUILD_TYPE=Release .." from the build directory will hide the warnings.
