### ISSUE TITLE
Bring back multithreading support for MacOS

### ISSUE THREAD

**Issue by Clockwork-Rat** [LadnerLab/PepSIRF#197]
Solve the compatibility issues between mac and open mp.

**Comment by SeanGolez** [comment]
I was able to get cmake to find omp on my machine (macOS Sonoma Version 14.5) by following these steps:
1. run `brew install libomp`
2. add `export OpenMP_ROOT=$(brew --prefix)/opt/libomp` to ~/.zshrc
3. add 'cmake_policy(SET CMP0074 NEW)' to CMakeLists.txt in the PepSIRF directory
4. recompile
