### ISSUE TITLE
Inclusion of a Logging System

### ISSUE THREAD

**Issue by ZwFink** [LadnerLab/PepSIRF#2]
A logging system should be implemented that allows messages of different severity. 

This logging system should have minimal impact on runtime performance and should have the following levels of logging granularity:
- **DEBUG** 
- **INFO**
- **WARN**
- **ERROR**

The system should be able to output to stderr/stdout or to a user-specified file. 
As a default, **ERROR** and **WARN** Message should be shown to the user. 
The user should be able to specify the 'level' of messages they want to see.

**Comment by jtladner** [comment]
Think carefully about compatibility with Qiime2 plugins.
