### ISSUE TITLE
Replicate Enrichment

### ISSUE THREAD

**Issue by ZwFink** [LadnerLab/PepSIRF#27]
Currently, only samples run in single-replicate and duplicate can be used to determine enrichment. Support for replicate (2+ samples) should be included. In this mode, 2+ samples can be included in the  input sample file. 

On its own, this change will produce an ambiguity in the scoring mechanism, where two thresholds are specified to determine enrichment; it becomes unclear whether every sample should have to meet the minimum threshold, or if only one sample needs to hit the threshold. To counter this, an argument should be added that allows the user to specify whether one sample needs to hit the lower threshold, or if every sample must hit the lower threshold.

**Comment by vidalrmartinez** [comment]
Closes with #114.

**Comment by vidalrmartinez** [comment]
Completed with creation of 'enrich' module. Closed with v1.4.0
