### ISSUE TITLE
Demux - Track individual index matches to diagnose sequencing problems

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#34]
Recently, there was an issue with the second index on a sequencing run that resulted in issues with demultiplexing. However, it took a while to diagnose the problem. As a standard part of demux, let's start reporting the % of reads for which I1 and I2 matches were found (individually).

**Comment by jtladner** [comment]
Let's have these metrics written to standard out. Let's also include information about the % of reads with matches to the variable sequence region ("--seq").

**Comment by jtladner** [comment]
@vidalrmartinez - Let's prioritize this next week. This has become even more important recently.

**Comment by vidalrmartinez** [comment]
Closed in release 1.3.2
