### ISSUE TITLE
A Warning Should be produced when duplicate sample names are present

### ISSUE THREAD

**Issue by ZwFink** [LadnerLab/PepSIRF#35]
All of the sample names in a sample list should be unique, but no warning is produced for the user when duplicate sample names are present. This can cause error downstream if the duplicate names are not noticed. Because of this, a warning should be produced when duplicates are encountered.

**Comment by jtladner** [comment]
In addition to checking for duplicate sample names, please also add a check for duplicate Index1/Index2 pairs.
