### ISSUE TITLE
Norm memory usage is unusually high with large input files

### ISSUE THREAD

**Issue by ZwFink** [LadnerLab/PepSIRF#39]
With larger input sizes to norm (>500MB), ```norm``` uses roughly 10x more memory than it is expected to.

**Comment by jtladner** [comment]
I'm seeing similarly large memory usage with the subjoin module. I was joining together 4 files, each ~1Gb individually. Merged together, the final file was 4.3Gb. However, I needed to provide the subjoin job with >100Gb of memory to get it to complete. Max RSS was 110.4 Gb.

**Comment by ZwFink** [comment]
I believe I have found the cause; copies of the data that are made are not discarded like they should be. The solution has not been figured out yet, but I'm working on it.

**Comment by jtladner** [comment]
Any progress on this issue? This is an important one and you are definitely the best person to tackle it.

**Comment by ZwFink** [comment]
Should be finished soon... The problem turned out to be non-trivial and requires more work than it initially seemed.

**Comment by jtladner** [comment]
Never solved, but not a priority.
