### ISSUE TITLE
Switch source of taxonomic info from sequence name to metadata file

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#50]
In order to increase flexibility and simplify management of metadata, we should change the way that the link module obtains the taxonomic information it uses. Instead of parsing this information from the names of the protein sequences, this information should be provided in a tab-delimited metadata file, which will include one column for the protein sequence names and a column for the metadata to be used to generate the linkage map. 

"-t [ --tax_id_index ] arg (=1)" should be changed to generally refer to the header name for the column the user wants to use for linkage map generation. 

To start, let's maintain the current functionality as an option, but add the option of supplying a metadata table instead.

**Comment by vidalrmartinez** [comment]
Closed in v1.3.0, but forgot to include in the merge commit.
