### ISSUE TITLE
--min_zscore not being set properly in s_enrich

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#54]
Tested tonight with v1.2.2 and v1.2.1, and the "--min_zscore" threshold is not being set properly in s_enrich. Based on some minimal testing, it appears that the maximum threshold provided between "--min_norm_score" and "--min_zscore" is being applied to both of these thresholds.

**Comment by jtladner** [comment]
This also seems to be a problem with p_enrich. It is not possible to specify different thresholds for "--zscore_constraint" and "--norm_score_constraint".

**Comment by ZwFink** [comment]
From this description, it seems that if a score meets the threshold for either, instead of both of the supplied thresholds, it will be counted as enriched?

**Comment by jtladner** [comment]
From what I've seen, I think that the higher of the two thresholds provided ends up being applied to both score types. So, if you used "--min_norm_score 100" and "--min_zscore 10", s_enrich would only report peptides with norm_score ≥100 AND zscore ≥100. 

Likewise, if you used "--min_norm_score 10" and "--min_zscore 100", you would get the same result.

**Comment by ZwFink** [comment]
This should be fixed, can you compile from the ```develop``` branch to confirm?

**Comment by jtladner** [comment]
Yup, fix looks good to me.
