### ISSUE TITLE
p_enrich includes two "-s" flags

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#55]
-s [ --samples ] arg              The name of the file containing sample pairs, denoting which samples are in duplicate. This file must be tab-delimited with one pair or 
                                    samples per line.
                                    
  -s [ --outfile_suffix ] arg       Suffix to add to the names of the samples written to output. For example, '_enriched.txt' can be used. By default, no suffix is used.

**Comment by vidalrmartinez** [comment]
I am changing -s to -a for the --outfile_suffix argument. My thought was a suffix is an affix - > a.

**Comment by jtladner** [comment]
Can we do "-x" instead?

**Comment by vidalrmartinez** [comment]
> Can we do "-x" instead?

Sure thing!

**Comment by ZwFink** [comment]
Closed in v1.3.0, but I forgot to include this in the merge commit.
