### ISSUE TITLE
Change handling of indexes to increase flexibility

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#57]
Currently, PepSIRF can only handle up to 2 indexes, and these indexes can either both be in R1 or one in R1 and one in R2. I would like to change the way that indexes are provided by the user in order to increase flexibility in the number and locations of the various indexes. 

This will include the following changes:

1. The requirements for the sample sheet should be changed. The sample sheet should now include a header row, and information from the sample sheet should be extracted based on column header, instead of column #. As before, there should be one column per index of interest, and each of these should have a unique header row. 

2. Instead of having multiple index flags, there should now be one flag for providing index location info and the argument provided with this flag should be a tab-delimited file with 5 columns: 1) index name, which should correspond to a header name in the sample sheet, 2) read name, which should be either "r1" or "r2" to specify whether the index is in "--input_r1" or "--input_r2", 3) index start location (0-based, inclusive), 4) index length and 5) number of mismatched to allow. Note: the last three columns correspond to the info currently provided on the command line with "--f_index" and "--r_index" (or  "--index1" and "--index2", with recent changes).

With these changes, the user should be able to specify an arbitrary number of indexes and explicitly specify to which read they can be found.

**Comment by jtladner** [comment]
Decided it wasn't worth the time to try to alter the code in PepSIRF. Instead, we can continue with the 1 nt DNA tag loop hole for getting col-sum values for very large files.

**Comment by vidalrmartinez** [comment]
Closed with release of version 1.5.0
