### ISSUE TITLE
Last bin is smaller that specified "--bin_size"

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#58]
In cases in which the library has been deeply sequenced, and therefore these is not a large number of peptides with zero count, the last bin can end up including fewer that the number of peptides specified with the "--bin_size" argument. 

These needs to be changed to ensure that there is never a bin with fewer members than specified by this argument.

**Comment by vidalrmartinez** [comment]
Closed in v1.3.0, but forgot to include in the merge commit.
