### ISSUE TITLE
Simplify scoring method selection for deconv module

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#61]
Currently there are three scoring strategies for the decov module. One (integer) is default, while the other two are selected by including optional flags: --summation_scoring or --fractional_scoring. 

I would like to simplify the selection of scoring strategy by creating a single --scoring_strategy flag to which one of the following strings must be provided: "integer", "fraction" or "summation". 

Please make "summation" default.

**Comment by vidalrmartinez** [comment]
Closed in v1.3.0, but forgot to include in the merge commit.
