### ISSUE TITLE
Standardize format of "--linked" file provided to deconv

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#64]
There are three different scoring methods that can be used in the deconv module. Currently, two of these methods expects a linkage map in one format, while the third expects a linkage map in a second format. The input format for the "--linked" file should be standardized, and should correspond to the format output by the link module. 

The link module outputs linkage maps with ":score" after each ID that is linked to a given peptide (in the second column of the tab-delimited file). This score is utilized in the summation scoring method, but not in the fractional or integer scoring methods. 

Because the fractional and integer scoring methods were established before the ":score" notation was added, the parsing of the "--linked" input files for these scoring methods is different, and this ":score" portion is not expected. 

We need to standardize so that the input "--linked" file is required to contain ":score" after the ID (i.e., format should be as output form link module), BUT the scores will not be utilized is the user chooses the Integer or Fractional scoring methods.

**Comment by vidalrmartinez** [comment]
Closed in v1.3.0, but forgot to include in merge commit.
