### ISSUE TITLE
ZLIB functionality doesn't compile properly on Mac. 

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#72]
Currently, the ZLIB functionality will not compile properly on a Mac. Therefore, if ZLIB is installed, "CMakeLists.txt" needs to be edited by the user, adding this line:

"set(ZLIB_FOUND 0)"

And, as a result, the compiled version does not support gzipped files as input to demux.

**Comment by jtladner** [comment]
Here is the error I see:

(base) client454:build jtladner$ make pepsirf
Scanning dependencies of target pepsirf_common
[  1%] Building CXX object CMakeFiles/pepsirf_common.dir/src/modules/parsers/options_parser.cpp.o
[  2%] Building CXX object CMakeFiles/pepsirf_common.dir/src/modules/core/options.cpp.o
[  3%] Building CXX object CMakeFiles/pepsirf_common.dir/src/modules/core/sequence.cpp.o
[  4%] Building CXX object CMakeFiles/pepsirf_common.dir/src/modules/core/file_io.cpp.o
In file included from /Users/jtladner/Documents/GitHub/PepSIRF/src/modules/core/file_io.cpp:1:
/Users/jtladner/Documents/GitHub/PepSIRF/include/modules/core/file_io.h:134:9: error: constructor for 'pepsirf_io::gzip_reader' must explicitly initialize the base class
      'std::istream' (aka 'basic_istream<char>') which does not have a default constructor
        gzip_reader( std::istream& input )
        ^
/Library/Developer/CommandLineTools/usr/include/c++/v1/istream:1467:64: note: 'std::__1::basic_istream<char>' declared here
_LIBCPP_EXTERN_TEMPLATE(class _LIBCPP_EXTERN_TEMPLATE_TYPE_VIS basic_istream<char>)
                                                               ^
1 error generated.
make[3]: *** [CMakeFiles/pepsirf_common.dir/src/modules/core/file_io.cpp.o] Error 1
make[2]: *** [CMakeFiles/pepsirf_common.dir/all] Error 2
make[1]: *** [CMakeFiles/pepsirf.dir/rule] Error 2
make: *** [pepsirf] Error 2

**Comment by jtladner** [comment]
I'm using MacOS Mojave: 10.14.6

**Comment by vidalrmartinez** [comment]
Closed in release 1.3.2
