### ISSUE TITLE
Highest Density Interval support for zscore module

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#78]
Currently, the "-t [ --trim ]" is used to specify how to discard outliers from each bin prior to calculating mean and standard deviation. This will trim an equal percentage of peptides from the lower and upper ends of the distribution. I would like to implement an alternative approach based on identifying the highest density interval of the distribution, and only using peptides that fall within this interval. 

I would like this option to be provided with -d [--hdi] option, I would like this method to become the default and, if both -d and -t are specified, I would like the -d option to override the -t option. 

This method is already implemented, in python, in the extensions script zscore.py (as --hpd). Please use this as a guide.

**Comment by vidalrmartinez** [comment]
Closed in release 1.3.2
