### ISSUE TITLE
Small bug in sujoin without sample list. 

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#83]
I ran subjoin today without providing a sample list (v1.3.2). It seemed to work fine, but a got a couple warnings regading not finding a sample called "Sample name". This is the header for the first column and should not be considered a real sample. Here is the full stdout:

$ pepsirf subjoin -f /Volumes/GoogleDrive/Shared\ drives/U24-ViromePepSeq/Manuscripts/2020-SARS-CoV-2/Analysis/PV1_combo/PV1.2/comboWR_norm.tsv -f /Volumes/GoogleDrive/Shared\ drives/U24-ViromePepSeq/Manuscripts/2020-SARS-CoV-2/Analysis/PV1_combo/PV1.5/PV1_combo7810_norm.tsv -o PV1.2-1.5_norm.tsv
WARNING: No sample name list has been given and provided file does not contain filename pairs. All scores will be output without filter.
WARNING: No sample name list has been given and provided file does not contain filename pairs. All scores will be output without filter.
PepSIRF (v1.3.2) 
Starting module Subjoin with arguments: 
 --filter_scores        /Volumes/GoogleDrive/Shared drives/U24-ViromePepSeq/Manuscripts/2020-SARS-CoV-2/Analysis/PV1_combo/PV1.2/comboWR_norm.tsv,
 --filter_scores        /Volumes/GoogleDrive/Shared drives/U24-ViromePepSeq/Manuscripts/2020-SARS-CoV-2/Analysis/PV1_combo/PV1.5/PV1_combo7810_norm.tsv,
 --filter_peptide_names false
 --duplicate_evaluation include
 --output               PV1.2-1.5_norm.tsv
 
WARNING: The sample Sequence name was not found in the input matrix, and will not be included in the output.
WARNING: The sample Sequence name was not found in the input matrix, and will not be included in the output.
Took 78.9359 seconds.

**Comment by jtladner** [comment]
Just tried the same command for a slightly different pair of matrices. In this case, PepSIRF seems to have interpreted the matrices as lists of matrices and sample lists. We need to re-evaluate how the different types of input files are being identified. 

command: pepsirf subjoin -f /Volumes/GoogleDrive/Shared\ drives/U24-ViromePepSeq/Manuscripts/2020-SARS-CoV-2/Analysis/PV1_combo/PV1.2/comboWR_norm_avgSBdiffratio.tsv -f /Volumes/GoogleDrive/Shared\ drives/U24-ViromePepSeq/Manuscripts/2020-SARS-CoV-2/Analysis/PV1_combo/PV1.5/PV1_combo7810_norm_avgSBdiffratio.tsv -o PV1.2-1.5_sbdr.tsv >sbdr_stdout.txt

[sbdr_stdout.txt.zip](https://github.com/LadnerLab/PepSIRF/files/5293664/sbdr_stdout.txt.zip)

**Comment by vidalrmartinez** [comment]
Closed in release of version 1.3.3.
