### ISSUE TITLE
Demux - index name error handling

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#96]
There are two files that are involved in specifying index/barcode sequences for each sample:

1. -s [ --samplelist ] arg, which provides index/barcode names associated with each sample. 
2. -i [ --index ] arg, which is a fasta formatted file that links the index/barcode names with the actual sequences. 

Currently, no error is generated in the event that an index/barcode name from --samplelist is not present in the --index file. Instead, no reads will be assigned to that sample. This behavior should be modified so that the user is warned any time that an index/barcode name from --samplelist is missing from --index. 

This will help with troubleshooting simple input file issues. For example, if there are typos in the index names in --samplelist or if the wrong fasta is provided with --index.

**Comment by vidalrmartinez** [comment]
I've now included a verification process that occurs during the initialization and parsing stage of the modules run. If at least one index/barcode name is not found in the fasta file that exists in a specified index1 or index2 column within the samplelist file, then a warning is provided stating so with the missing index/barcode name listed. The listed missing names are one per line in the terminal.

**Comment by vidalrmartinez** [comment]
Issue has been tested by removing index/barcode names from the --index file that are present in the --samplelist file. The warning message: "WARNING: The following index/barcode names from '--samplelist' are not present in the '--index' file:" followed by a listing of each name not found in the --index file. This issue will be closed in release 1.3.6.
