### ISSUE TITLE
Zscore - "Error: vector"

### ISSUE THREAD

**Issue by jtladner** [LadnerLab/PepSIRF#97]
Currently, if the user mistakenly provides a score matrix to the zscore --bins argument, instead of a bins file, a cryptic error is generated: "Error: vector".

Modify the error reporting to make the message more user friendly. Not sure exactly what the message should be. It depends on the nature of the test that triggers the error.

**Comment by vidalrmartinez** [comment]
The cryptic message occurred when an incorrect file was provided for the --bins input. To avoid this, a check was added following the input of a file for the --bins option. The correct file type is verified by checking the second row of the file does not contain doubles/floats or infinity or NaN. A score matrix is the likely wrong file to provide so looking at the second row of a tsv is a simple way to check that only peptide names are provided. If a number or inf/nan value is found, the run terminates with the following error message: "Bins file 'filename' provided contains score values. Verify the bins file is valid.
Note: this error could also be triggered IF your peptide names include ‘inf’ or ‘nan’ (case insensitive).". This issue has been tested to verify incorrect data in the tsv provided is caught and generates an error. The only concern, which is noted in the error message, is if the name contains nan or inf, there is potential it may trigger an error thrown. Likely if the name were to start with nan or inf, but not if other characters preceed it. This issue will be closed with release 1.3.6.
